export const machines = [
  'Mercedes-Benz GLE Coupe',
  'Ford Explorer',
  'Toyota Corolla',
  'Lamborghini LM002',
  'Mitsubishi Lancer Evolution VIII',
  'BMW 7 Series',
  'Mercedes-Benz 500E/E500',
  'Chevrolet Camaro IROC-Z',
  'Lincoln Continental',
  'Toyota Corolla',
  'Cadillac V16',
  'Mazda RX-7',
  'Volkswagen Type 2',
  'Chevrolet Corvette ZR1',
  'Ford Taurus',
  'Ford Country Squire',
  'Chevrolet Corvette V8',
  'Jaguar XJ6',
  'Rolls-Royce Silver Ghost',
  'Porsche Panamera',
  'Range Rover',
  'Jeep MB',
  'Chrysler Airflow',
  'Aston Martin DB5',
  'Chrysler Minivans',
  'Porsche 930',
  'Ford Mustang 5.0',
  'Bugatti Veyron',
  'Subaru WRX',
  'Lotus Esprit',
  'Audi A4',
  'Lexus LS 400',
  'Toyota Camry',
  'Honda Accord',
  'Ferrari F40',
  'Lincoln Continental',
  'Honda Civic Coupe',
  'Lancia Stratos',
  'Lamborghini Countach',
  'Mazda Miata MX-5',
  'Porsche 917',
  'Nissan Skyline GT-R',
  'Chevrolet Camaro',
  'Ford Mustang',
  'Lamborghini Miura',
  'Ford V8'
]